const api = require('../../services/api');
Page({data: {items: [], title: '', story: '', experience: '', error: '', busy: false},
  async onShow() { try { this.setData({items: await api.request('/memories'), error: ''}); } catch (error) { this.setData({error: error.message}); } this.resumeJob(); },
  resumeJob() { clearInterval(this.timer); const id = wx.getStorageSync('memory-job'); if (!id) return; this.timer = setInterval(async () => { try { const result = await api.request(`/jobs/${id}`); this.setData({jobText: {queued: '等待处理', running: '正在整理经验', succeeded: '整理完成，请确认', failed: '整理失败，请重试'}[result.status]}); if (['succeeded', 'failed'].includes(result.status)) { clearInterval(this.timer); wx.removeStorageSync('memory-job'); await this.onShow(); } } catch(error) { this.setData({error: error.message}); } }, 2000); },
  field(event) { this.setData({[event.currentTarget.dataset.field]: event.detail.value}); },
  async save() { this.setData({busy: true}); try { await api.request(this.data.editId ? '/memories/' + this.data.editId : '/memories', this.data.editId ? 'PUT' : 'POST', {title: this.data.title, story: this.data.story, original_experience: this.data.experience, photo_id: this.data.photoId || null, plant_id: getApp().globalData.plantId || null}); this.setData({title: '', story: '', experience: '', editId: '', photoId: '', photoUrl: ''}); await this.onShow(); } catch (error) { this.setData({error: error.message}); } finally { this.setData({busy: false}); } },
  edit(event) { const item = this.data.items.find(m => m.id === event.currentTarget.dataset.id); this.setData({editId: item.id, title: item.title, story: item.story, experience: item.original_experience}); },
  async choosePhoto() { try { const media = await new Promise((resolve, reject) => wx.chooseMedia({count: 1, mediaType: ['image'], success: resolve, fail: reject})); const result = await api.upload(media.tempFiles[0].tempFilePath, getApp().globalData.plantId); this.setData({photoId: result.image_id, photoUrl: media.tempFiles[0].tempFilePath}); } catch(error) { this.setData({error: error.message || '图片上传失败'}); } },
  async structure(event) { try { const job = await api.request(`/memories/${event.currentTarget.dataset.id}/structure-rule`, 'POST'); wx.setStorageSync('memory-job', job.job_id); this.resumeJob(); } catch (error) { this.setData({error: error.message}); } },
  async toggle(event) { const id = event.currentTarget.dataset.id; try { await api.request(`/memories/${id}/enabled`, 'PUT', {enabled: event.detail.value, confirmed: true}); await this.onShow(); } catch (error) { this.setData({error: error.message}); } },
  onHide() { clearInterval(this.timer); }, onUnload() { clearInterval(this.timer); }
});
